name: Publish Docker Image

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - feature/*
      - chore/*

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.QUANTDIVE_USERNAME }}
          password: ${{ secrets.QUANTDIVE_PASSWD }}

      - name: Build and publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/emotive-academy/quantdive:latest