name: Unit test CI 

on:
  push:
    branches:
      - chore/*
      - feature/*
      - fix/*
      - release/*
      - bug/*
      - hotfix/*
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install source code
        run: |
          pip install .

      - name: Run tests
        run: pytest ./tests

      - name: Lint code
        run: flake8 src/